### ISSUE TITLE
NoSuchMethodError DispatchEventFromNative 4.4 devices

### ISSUE THREAD

**Issue by salexwm** [mrmaffen/vlc-android-sdk#15]
I'm using vlc sdk version 3.0.0 on real arm 4.4 device

dependency from build.gradle 
compile 'de.mrmaffen:vlc-android-sdk:3.0.0'

Here's error from logcat:
```
01-18 09:31:35.020 11454-11454/? E/AndroidRuntime: 
	FATAL EXCEPTION: main
   Process: com.project, PID: 11454
   java.lang.NoSuchMethodError: no method with name='dispatchEventFromNative' signature='(IJJ)V' in class Lorg/videolan/libvlc/VLCObject;
       at java.lang.Runtime.nativeLoad(Native Method)
       at java.lang.Runtime.doLoad(Runtime.java:428)
       at java.lang.Runtime.loadLibrary(Runtime.java:369)
       at java.lang.System.loadLibrary(System.java:526)
       at org.videolan.libvlc.LibVLC.<clinit>(LibVLC.java:192)
       at com.project.VideoActivity.createPlayer(VideoActivity.java:176)
       at com.project.VideoActivity.onResume(VideoActivity.java:93)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1197)
       at android.app.Activity.performResume(Activity.java:5422)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2989)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3032)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2434)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5333)
       at java.lang.reflect.Method.invokeNative(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
       at dalvik.system.NativeStart.main(Native Method)
```
Code in VideoActivity is almost the same as in example project.

On 5.0+ works fine.

**Comment by mrmaffen** [comment]
Please contact the videolan dev team directly. I merely publish the SDK.
